### ISSUE TITLE
sha AAAI2018Joint问题请教

### ISSUE THREAD

**Issue by carrie0307** [shalei120/shalei120.github.io#1]
ShaLei您好：
    读到您在2018AAAI发表的论文《Jointly Extracting Event Triggers and Arguments by Dependency-Bridge RNN and Tensor-Based Argument Interaction》，有几处问题想请教，希望您能不吝赐教，谢谢！

1. 您的实验是在ACE2005数据集进行的，请问在ACE2005数据上您是如何定义sentence的呢?是按照[ACE2005 Event Guidelines](https://www.ldc.upenn.edu/sites/www.ldc.upenn.edu/files/english-events-guidelines-v5.4.3.pdf)中提出**An Event extent is a sentence within which a
taggable Event is described**将event extent部分内容作为包含event的sentence，还是自行对ACE2005中的articles进行了sentence划分呢?

2. 进行MaxPooling的公式7中，请问k值是什么意思?

3. 您在Experiment部分写到，通过StandFordParser将其中标注为NP的token作为了candidate argument；如果只是将标注为NP的single token作为candidate argument,那么如何实现对multi-token-level argument的识别呢？如何实现对非NP的argument识别呢(例如，now等时间概念)?另外，请问在确定candidate triggers时是否也借助了StandFordParser的标注呢？

4. 在ACE2005数据中，论元对应的entity包括extent和head两种精度的描述；请问在判断是否识别出argument计算F值等指标时，是从extent精度衡量还是从head精度衡量呢?

期待得到您的答复，谢谢啦！

**Comment by shalei120** [comment]
already replied in email

**Comment by carrie0307** [comment]
邮件已收到，我再多多自己研究研究，谢谢您啦！
